#!/bin/sh
rm -rf ./generated
mkdir ./generated
docker build -t xdr-gen .
docker run -it \
	--mount type=bind,source="$(pwd)"/generated,target=/data/src/generated \
	xdr-gen
mv ./generated/stellar-xdr_generated.js ./generated/stellar-xdr_generated.ts